### ISSUE TITLE
Inconsistent boldness in event list

### ISSUE THREAD

**Issue by AlexanderHarrison** [AlexanderHarrison/TrainingMode-CommunityEdition#16]
Either make every custom event bold, or none.

**Comment by NickCondron** [comment]
I'm pretty sure the boldness was a reflection of which events were written in C in the newer style and which were written in ASM. I agree it doesn't make sense to have different text styles in the event menu. However, I think it makes sense to decide which events should be deprecated/replaced/maintained and create separate issues for them.
