### ISSUE TITLE
Shorthop versus Fullhop press

### ISSUE THREAD

**Issue by 901Austin** [AlexanderHarrison/TrainingMode-CommunityEdition#175]
An OSD for whether a shorthop or fullhop press was inputted would be absolutely awesome for practicing shorthop wavedashes. 
What I mean by that, to clarify, is making sure a jump press that would result in a shorthop is used when wavedashing - so that in case of a failed wavedash (mistiming the trigger press), a short hop results rather than full hopping. Hope that makes sense. Thank you for your work!

**Comment by renzoredmarth** [comment]
This is already included

**Comment by 901Austin** [comment]
> This is already included

Ohhhhh, it's under Wavedash Info OSD. Sorry about that! THANK YOU!
