### ISSUE TITLE
Utilize existing Firefox visualization code

### ISSUE THREAD

**Issue by NickCondron** [AlexanderHarrison/TrainingMode-CommunityEdition#77]
There is assembly code that seems to be part of a WIP feature to draw a line or something for the firefox angle of fox/falco.

https://github.com/AlexanderHarrison/TrainingMode-More/blob/4a4054dc3b299f0339f5def80a7b928400221eb6/ASM/Additional%20Codes/GX%20Draw/Main.s#L18

It would be interesting to:

1. Get the code working
2. Port the code to C -- like how DI draw was done here https://github.com/AlexanderHarrison/TrainingMode-More/blob/4a4054dc3b299f0339f5def80a7b928400221eb6/src/lab.c#L2051
3. Utilize the feature in some sort of spacie tech event or something cool like that.

**Comment by CDSSBM** [comment]
This was actually implemented in an older version but eventually removed for whatever reason.
It works for both Fox and Falco

https://streamable.com/r7kiy0?src=player-page-share

**Comment by NickCondron** [comment]
Closing in favor of implementing this sort of thing in C eventually. The video posted showed the existing implementation was quite ugly haha.
